### ISSUE TITLE
Program refuses to accept CS2 Root Folder

### ISSUE THREAD

**Issue by HurgBurg** [KingHabib/CS-Jukebox#11]
Regardless of whether I run with admin privs or not, the program refuses to accept my game folder as the directory. For posterity, this is the exact directory attempting to be used. 
D:\Steam\steamapps\common\Counter-Strike Global Offensive\game
Without it accepting the directory, I am incapable of moving forward to actually use the program. Please advise.
![image](https://github.com/zzhabib/CS-Jukebox/assets/150381101/28ff91c7-7e90-4743-8842-7d833ce87fdb)

**Comment by AlexSBlackburn** [comment]
If you downloaded the program using the link in the Readme then you're using the old version that isn't compatible with CS2 (the readme link hasn't been updated). The latest release is available here: https://github.com/zzhabib/CS-Jukebox/releases
