### ISSUE TITLE
The program won't start (Windows 11)

### ISSUE THREAD

**Issue by Crackhog** [KingHabib/CS-Jukebox#9]
I installed .NET as instructed, however, instead of a popup that says that .NET isn't installed appearing, I get no feedback whatsoever, and the program doesn't start. I also tried running the program as administrator, to no success.

I would like to know what I can do to give further insight into the problem (for example, by uploading any log files, if present). Also, it would be nice if you could give me troubleshooting support via Discord instead of here. My Discord username is `@crackhog`

**Comment by zzhabib** [comment]
Hmm, my best guess is that you may be missing the `gamestate_integration_jukebox.cfg` file. It should be in the same directory as the `.exe`. Unfortunately that's the best advice I can give right now. I don't have any logging set up for this application.

**Comment by Crackhog** [comment]
That doesn't seem to be the case, unfortunately. I found a solution, albeit a somewhat ugly one, by putting the program with all its files into my .NET installation folder and running the .dll using the dotnet command directly. I was hoping that this was just a temporary solution, but if there's nothing I can do, then this is more than enough.

**Comment by pinlupe** [comment]
How exactly you do that? I'm having the same issue

**Comment by Speculonse** [comment]
> That doesn't seem to be the case, unfortunately. I found a solution, albeit a somewhat ugly one, by putting the program with all its files into my .NET installation folder and running the .dll using the dotnet command directly. I was hoping that this was just a temporary solution, but if there's nothing I can do, then this is more than enough.

Hello, I don't understand exactly how you did ? Does it still work ?
